README.md
src/js/build-html.js
src/js/default-options.js

Allow list item class to be specified using the `listItemClass` configuration option, which defaults to `'toc-list-item'`.
See issue #12.

List item class

---

README.md
package.json
src/js/build-html.js
src/js/default-options.js
src/js/parse-content.js
test/index.js

- [patch] `includeHtml` option to mirror markup from the headings in the TOC (#14).
- [patch] `listItemClass` will be omitted if an empty string in passed.
- [dev] `test:watch` command.
- [dev] more tests.

Heading html

---

README.md
package.json

I would have added node-inspector the devDependencies in order to enable the test:debug script, but that would currently break `npm install` for folks on node v7 because of node-inspector/node-inspector#950.
For now, I've documented that `npm install node-inspector` has to be run manually on node v6 or lower.

Various minor tweaks

---

src/js/build-html.js

When I go directly to a link, it highlights the link before the
one I am visiting. I put some console.log() statements in and it looks
like it's some sub-pixel rounding problem?
I experience the issue on my own site and also the official tocbot
docs page, in both chromium and firefox (on linux). This patch fixes
the issue for my site in both browsers.

Make current section highlighted instead of previous

---

README.md
src/js/build-html.js
src/js/default-options.js

I see that unordered lists were replaced with ordered lists, per https://github.com/tscanlin/tocbot/pull/73/files, but might you be amenable to supporting both, even though `ol` is indeed compelling semantically?
Thank you!

Re-add support for unordered lists

---

README.md
src/js/build-html.js
src/js/default-options.js
src/scss/_page-styles.scss

If `hasInnerContainers` is set to `true`, the `offsetTop` of the heading is recursively added up with the `offsetTop` values of it's parent positioned containers, until the `contentSelector` container is reached. Therefore the `contentSelector` container should have `position: relative`. If not, the document root is reached.

suggestion for issue #135

---

README.md
pages/skipRendering.js
src/components/Template/Tocbot/index.js
src/components/Template/index.js
src/js/default-options.js
src/js/index.js

Hello and thanks for a great library @tscanlin :) 
I'm about to use it on https://codedutravail-dev.num.social.gouv.fr/kali/1747-convention-collective-nationale-des-activites-industrielles-de-boulangerie , a french public website that helps employees understand work laws. As you can see there's some heavy table of contents. I don't want to completely delegate the generation of the DOM to tocbot, only use the scroll listener feature to autofocus the right one.
In this PR I'm therefore introducing a `skipRendering` option that does just that.
Let me know if that's a feature you'd be interested in integrating into the core tocbot, and in which case what you'd like me to improve on this PR!

introduce new skipRendering option

---

index.d.ts

Hi there 👋 
As mentioned in the original issue (#162), the TypeScript DOM lib doesn't have a `ClickEvent` interface, but does have a `MouseEvent` type.
closes #162
Cheers!

fix: Typescript definition for onClick event

---

README.md

Had a bit of trouble trying to figure out why certain options weren't working, until I realized the CDN files I was importing were obsolete. Hope this helps someone.
(Not sure what the GitHub Pages workflow is, but same outdated content appears on http://tscanlin.github.io/tocbot/ as well and should be updated.)
Great product btw!

Update CDN links

---

src/utils/make-ids.js

Fix an issue in `make-ids.js` where headers with a forward slash (eg, `some text to include/exclude`) was not properly sanitized (eg, `some-text-to-include/exclude`, which then caused an error with tocbot). With this PR, forward slashes are replaced with a dash (eg, `some-text-to-include-exclude`).

fix generation of a proper id for headers with a forward slash

---

README.md
src/components/Template/TryIt/index.js
src/js/default-options.js
src/js/index.js
src/js/update-toc-scroll.js
src/utils/make-ids.js
src/utils/update-visible-toc.js

Add scroll visible util

---

index.d.ts

When trying to use `disableTocScrollSync` in one of our projects, ts complained about the option missing in the declaration file.
I also added the option `basePath`
Thanks

Add typescript definition for basePath and disableTocScrollSync

---

README.md

Fixed the markdown formatting.

docs: fix link to MIT license

---

index.d.ts

Unfortunately `scrollSmoothOffset` is missing in the type declarations which causes some TS issues. This should fix it.

Add scrollSmoothOffset to type declarations

---

index.d.ts

According to https://developer.mozilla.org/en-US/docs/Web/API/MouseWheelEvent the MouseWheelEvent is deprecated and should be replaced by WheelEvent (https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent) - this change is important since in version 4.4.0 and onwards of Typescript this breaks the build process for repos depending on the library. See https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029#issuecomment-907141728

Fix Deprecated Type

---

index.d.ts

Hey again, ran into a blocking problem where using `refresh` with custom options in TypeScript throws an error because the `index.d.ts` file doesn't have the options in the signature. Since the file isn't generated, I'm opening this PR to manually correct it.
@tscanlin, if you approve, feel free to merge and publish it yourself 👍🏻

Fix refresh type in index.d.ts

---

.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml

This PR updates the github workflow run with npm 18.x, thus eliminating errors and warnings about the use of deprecated action versions that will be removed in the future.
More specifically, e.g. this error message is gone now:
```
This version of the CodeQL Action was deprecated on January 18th, 2023,
and is no longer updated or supported. For better performance, improved
security, and new features, upgrade to v2. For more information,
see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
```

Updating Github workflow to npm 18.x

---

README.md
src/js/build-html.js

This PR corrects the CDN download URLs by bumping the outdated versions given there.
It also removes a example site that does not exist any more and fixes a typo.

CDN download URL: bump outdated version

---

.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml
.github/workflows/release.yml

This PR bumps GitHub action workflows to latest versions, thus avoiding deprecation warnings as e.g. seen [here](https://github.com/tscanlin/tocbot/actions/runs/8222329790).

Bump GitHub action workflows to latest versions

---

src/js/build-html.js
src/js/scroll-smooth/index.js
src/js/server-render.js

add a server render util

---

src/js/build-html.js

switch to getByElementId to fix encoding edge case for #377

switch to getByElementId to fix encoding edge case

---

src/components/Template/Tocbot/index.js
src/js/build-html.js

fix highlight issue after clicking and scrolling to the bottom
Addresses: #376

fix highlight issue after clicking and scrolling to the bottom

---

index.d.ts

Since I use TS frequently, I hope to add the previously missing type declarations.
Meanwhile, I want to change the default export to ES6 syntax, as this might make development more convenient. 😺

Update type declaration

---

src/scss/_tocbot-core.scss

Fix for #387 
Improve a11y by making focused section expand.

add css to make tocbot more a11y friendly
