.travis.yml, README.md, package.json, script/render.js, src/js/build-html.js, src/js/default-options.js, src/scss/_page-styles.scss, src/scss/_tocbot-core.scss, src/scss/_tocbot-responsive.scss, src/scss/styles.scss, src/scss/tocbot.scss, src/templates/Main.jsx, src/templates/wrapper.html, travis-deploy.sh
add position fixed selector option and start using travis
=> add position fixed selector option and use travis-ci

README.md, package.json, src/js/build-html.js, src/js/index.js, src/js/parse-content.js, test/index.js
=> fix to prevent errors from being thrown if elements are not present and

README.md, package.json, src/scss/_tocbot-core.scss, travis-deploy.sh
This should address #16 and #17
=> add style and script to commit dist files

README.md
=> updated react support todo

CHANGELOG.md, README.md, next.config.js, package.json, pages/_document.js, scripts/fix-export.js, server.js, src/components/Template/index.js, src/js/default-options.js, src/js/index.js, src/js/scroll-smooth/index.js, src/scss/styles.scss, test/imageDiff.js, test/integration_test.js, test/steps_file.js
Fix for #67 
replace zenscroll with a custom smooth scroll implementation adapted from: https://www.sitepoint.com/smooth-scrolling-vanilla-javascript/
This fixes next.js errors and will be a major version bump.
=> get new smooth scroll implementation working

src/js/build-html.js, src/scss/_tocbot-core.scss, test/data/rendered.html
=> use ol instead of ul

src/js/index.js
=> remove object.assign to fix ie

src/utils/make-ids.js
=> add id gen util

src/utils/make-ids.js
This PR fixes duplicated IDs in the existing document.
=> Fix duplicated ID

README.md, src/components/Template/Tocbot/index.js, src/js/build-html.js
=> fix offset

src/js/index.js
=> fix: browserify

README.md, index.d.ts, src/js/parse-content.js
fix #157 
Note: I couldn't run the tests (`Cannot read property 'init' of undefined` in beforeEach :confused: ), but I obviously tested manually.
Feel free to fix my (probable) typos, since english isn't my native language.
An example of use-case:
``` js
headingLabelCallback: heading => {
if (heading.length > 71) {
heading = heading.substring(0, 71) + '...'
}
return heading 
})
}
```
=> Added callback to change labels

README.md
=> Update sass import documentation

README.md
a little snippet about using headingsOffset to solve problems with css scroll-padding
=> Adding to the documentation 

README.md, pages/_config.js, src/components/Template/Tocbot/index.js, src/components/Template/index.js
fix fixed header support and update docs.
the old CSS way seems to have stopped working due to browser changes. Someone left a comment on an issue to this effect but it was removed.
Anyway, this PR should solve these issues and make it easier to deal w/ in pure JS:
https://github.com/tscanlin/tocbot/issues/161#issuecomment-745743695
https://github.com/tscanlin/tocbot/issues/170
=> fix fixed header support and update docs

package-lock.json, src/js/scroll-smooth/index.js
=> fix for encoded URIs

src/js/index.js
misspell toble of content -> table of content
=> Update index.js comment

CHANGELOG.md, README.md, src/js/build-html.js, src/js/index.js
This PR fixes a few typos I spotted. It also changes a few links from `http`to `https` protocol.
=> Fixes typos

src/js/build-html.js
classname toggling optimization
=> classname toggling optimization

.github/workflows/node.js.yml, index.d.ts, src/js/update-toc-scroll.js, src/scss/_tocbot-core.scss
adjust scroll logic to do smaller changes when item is out of view.
For #323
=> adjust scroll logic to do smaller changes

dist/tocbot.cjs, package.json
=> fix use for cjs

src/components/Template/index.js, src/js/index-dist.js
Fix for #385 
This should check if HTML elements are used for some of these global vars to prevent issues.
=> fix for global vars caused by certain ids causing issues with init
